### ISSUE TITLE
This is extremely cool, please make it work with floats and implement some unit tests. <eom>

### ISSUE THREAD

**Issue by borismus** [aplbrain/npyjs#1]

**Comment by j6k4m8** [comment]
@borismus thank you for the kind words! 

Work on npyjs is in progress, but at a low priority. Pull-requests welcome if you have time, and bug-reports also welcome if you don't! :)

**Comment by adclose** [comment]
I totally echo this it would be awesome if it worked with floats

**Comment by j6k4m8** [comment]
I also totally echo this :)

I've begun reworking some of the code to prepare for adding float support. If either of you (cc @adclose @borismus) have any interest in contributing some engineering chops or unit tests, would be hugely appreciative, as this is unfortunately a very low priority project.

Otherwise, stay tuned, this is in the works!

**Comment by j6k4m8** [comment]
Take a look and see if this latest v0.1.1 release works for your use-case; I think we can close this issue!

**Comment by j6k4m8** [comment]
Feel free to reopen or start a new issue if the latest release hasn't met your needs!

**Comment by adclose** [comment]
I haven’t had time to check but will let you know

Thanks 
Aaron
